[project]
name = "nlp-deeplearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.8",
    "jpype1==1.4.1",
    "konlpy==0.6.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.6.1",
    "seqeval>=1.2.2",
    "tensorflow>=2.20.0",
    "uvicorn>=0.39.0",
]
